### ISSUE TITLE
skeleton

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#1]

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#11](https://github.com/zerocracy/judges-action/issues/11), [#12](https://github.com/zerocracy/judges-action/issues/12), [#13](https://github.com/zerocracy/judges-action/issues/13) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#11](https://github.com/zerocracy/judges-action/issues/11), [#12](https://github.com/zerocracy/judges-action/issues/12) are still not solved; solved: [#13](https://github.com/zerocracy/judges-action/issues/13).

**Comment by 0pdd** [comment]
@yegor256 all 3 puzzles are solved here: [#11](https://github.com/zerocracy/judges-action/issues/11), [#12](https://github.com/zerocracy/judges-action/issues/12), [#13](https://github.com/zerocracy/judges-action/issues/13).
