### ISSUE TITLE
find-all-issues.rb

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#102]
Let's add a new judge, which will take the smallest issue in a repository (using `issue-was-opened` facts) and then add more facts, with smaller numbers. Such issues definitely exist in the repository, anyway.

**Comment by Yegorov** [comment]
> which will take the smallest issue in a repository

What the means "smallest issue"?

> with smaller numbers

What is it? (maybe issue without comments?)

@yegor256 Can you give more information about this?

**Comment by yegor256** [comment]
@Yegorov first, we scan all `issue-was-opened` facts and find the smallest value of their `issue` properties. This is the "smallest issue" in the repository that we are aware of. However, this is not the smallest number in GitHub: there are smaller numbers too. This happens because `github-events.rb` doesn't scan all events, but only the latest 1000 (or so). In order to fix this, we should add `issue-was-opened` events to the factbase, pretending we've seen them in `github-events` (even though we haven't).

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Yegorov sure, please!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.55`
