### ISSUE TITLE
`average_build_duration` into QoS

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#155]
Let's add `average_build_duration` metric to the `quality-of-service.rb` script. It should calculate the average time (in seconds) of all recent GitHub Action workflow runs.

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Yegorov go ahead, please

**Comment by Suban05** [comment]
@yegor256 Please close
