### ISSUE TITLE
average_pull_rejection_rate

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#156]
Let's add `average_pull_rejection_rate` metric to the `quality-of-service.rb` script. It should calculate the relationship between recently rejected pull requests and all recently submitted pull requests.

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Yegorov sure, go ahead

**Comment by Suban05** [comment]
@yegor256 Please close
