### ISSUE TITLE
average_stars and average_forks

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#158]
Let's add `average_stars` and `average_forks` metrics to the `quality-of-service.rb` script. They should calculate how many, on average, are there GitHub stars/forks are in all repositories.

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Yegorov sure, go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.37`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.37`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.37`
