### ISSUE TITLE
contributors are missing in `release-published` fact

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#166]
When we detect `release-published` fact in `github-events.rb`, we don't put the list of contributors into it, but we should. Let's call this property `contributors` and let it keep the array of GitHub IDs.

**Comment by Yegorov** [comment]
@yegor256 may I try this one?

**Comment by yegor256** [comment]
@Yegorov please, go ahead

**Comment by Suban05** [comment]
@yegor256 please close it. It's also fixed
