### ISSUE TITLE
`commits`, `hoc`, and `last_commit` are missing in `release-published`

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#167]
When we detect `release-published` fact in `github-events.rb`, we don't count commits and hoc of the release, but we should. Let's do it.

Also, now we don't record any information about its commits. Let's put the `last_commit` property into the fact with the SHA of the last commit that was released in this release.

**Comment by Yegorov** [comment]
@yegor256 may I try this one?

**Comment by yegor256** [comment]
@Yegorov sure, go ahead

**Comment by Suban05** [comment]
@yegor256 please close
