### ISSUE TITLE
`average_release_hoc_size` into QoS

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#193]
Let's add `average_release_hoc_size` metric to the `quality-of-service.rb` script. It should calculate the average number of hits-of-code in a published release. Also, let's add `average_release_commits_size` with the average number of commits in a release.

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Yegorov sure, go ahead
