### ISSUE TITLE
`total_issues` and `total_pulls` into DoT

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#200]
Let's add `total_issues` metric to the `dimensions-of-terrain.rb` script. It should 
calculate the total number of all issues every reported in all repositories (excluding pulls).

Let's also calculate `total_pulls`.

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Yegorov sure, go ahead
