### ISSUE TITLE
`total_files` into DoT

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#202]
Let's add `total_files` metric to the `dimensions-of-terrain.rb` script. It should calculate the total number of files in all repositories. Maybe GitHub API can help us with this. If not, we probably need to `git clone` all repositories one by one and count files in them.

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Yegorov please, go ahead
