### ISSUE TITLE
`pull-was-reviewed` is coming for the person who didn't do the review

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#209]
Check this report: https://zerocracy.github.io/judges-action/zerocracy.html

Search for `pull-was-reviewed` and `zerocracy/baza#154`. As you see, we have two reports for the same issue, but for two different `who`s. While the review was done by one person (`526301`), we got two facts. Something is wrong with `github-events.rb`.

<img width="1566" alt="Screenshot 2024-08-01 at 08 21 08" src="https://github.com/user-attachments/assets/a820b252-0e72-4245-bc86-f298033bb419">

It happened here: https://github.com/zerocracy/baza/pull/154

**Comment by Suban05** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Suban05 yes, please try

**Comment by Suban05** [comment]
@yegor256 for `zerocracy/#43` `pull-was-reviewed` is also incorrectly defined?
![2024-08-01_20-08-40](https://github.com/user-attachments/assets/af58132d-e22d-4467-a912-c1e2e1fa5647)

**Comment by yegor256** [comment]
@Suban05 yes, the same problem

**Comment by Suban05** [comment]
@yegor256 Do I understand correctly that the user who submitted a pull request should not be the reviewer?

**Comment by yegor256** [comment]
@Suban05 yes, of course. The reviewer is the one who submitted a review. Well, technically, maybe, it should be possible for a PR author to submit a review. But this is not what has happened in our cases.

**Comment by Suban05** [comment]
@yegor256 I added this code
```rb
if json[:payload][:pull_request][:user][:id] != json[:payload][:review][:user][:id] && 
json[:payload][:action] == 'created'
```
instead of
```rb
case json[:payload][:action]
when 'created'
```      
If I understood everything correctly, then this should help, but I don't understand how to write test in this repository to be sure.

**Comment by yegor256** [comment]
@Suban05 I think I understand the problem. When JSON arrives on `PullRequestReviewEvent`, its structure looks like this:

```
{
  actor: { id: ... } # this is the author of the pull request
  payload: {
    pull_request: {
      user: { id: ... } # this is also the author of the PR
    },
    review: {
      user: { id: ... } # this is the guy who created the review
    }
  }
}
```

We are using (by mistake) the id from the `actor`. Am I right?

**Comment by yegor256** [comment]
@Yegorov I will create a test now, to show you an example

**Comment by yegor256** [comment]
@Suban05 I added the test in 10b780c, hope it helps

**Comment by Suban05** [comment]
@yegor256 `actor` is the guy who created the review comment, he is not a reviewer, as far as I understand. But he must match field `json[:actor][:id]`

**Comment by yegor256** [comment]
@Suban05 the `PullRequestReviewEvent` event arrives when a new review is submitted: https://docs.github.com/en/rest/using-the-rest-api/github-event-types?apiVersion=2022-11-28#pullrequestreviewevent Not when a comment is posted, but when a review is created.

**Comment by yegor256** [comment]
@Suban05 try to read the timeline of events in one of our repositories (using `curl`) and see the exact structure of JSON that is coming from there. This should help us understand what's going on.

**Comment by Suban05** [comment]
@yegor256 okay, thanks

**Comment by Suban05** [comment]
@yegor256 Points have been earned for reviewing a user's own pull request in this pull request https://github.com/yegor256/judges/pull/93. Was it a bug, or did it happen because the pull request was created before the change https://github.com/zerocracy/judges-action/pull/215?

**Comment by yegor256** [comment]
@Suban05 indeed, it happened before we release the bug fix

**Comment by Suban05** [comment]
@yegor256 please close
