### ISSUE TITLE
`pull-was-merged` details are not sufficient

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#211]
In `github-events.rb`, when we process `PullRequestEvent`, we created `pull-was-merged` fact. There, we only count the number of comments, but it's not enough and not accurate. Instead, let's count:

  * `comments` - total number of comments (we count them now)
  * `comments_to_code` - how many comments posted to the source code
  * `comments_resolved` - how many comments of reviewers were resolved
  * `comments_by_author` - how many comments the author of the PR posted
  * `comments_by_reviewers` - how many comments PR reviewers posted
  * `comments_appreciated` - how many comments were appreciated (emoji posted) by people who are not their authors

**Comment by Suban05** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Suban05 sure, go ahead

**Comment by Suban05** [comment]
@yegor256 I'm not sure, but there seems to be no way to find out anything about resolved conversations using the Github API
https://github.com/orgs/community/discussions/9175

**Comment by yegor256** [comment]
@Suban05 maybe we can use GraphQL API, as [suggested](https://github.com/orgs/community/discussions/9175#discussioncomment-9008230)?

**Comment by Suban05** [comment]
@yegor256 okay, I will try

**Comment by Suban05** [comment]
@yegor256 maybe it would be better to add interaction with the `graphql-client` library to `fbe` in the same way as it was done with `octokit`?

**Comment by yegor256** [comment]
@Suban05 sure!

**Comment by Suban05** [comment]
@yegor256 I want to add a new class to solve this issue, but I'm not sure if it is necessary or not. Would it be redundant to create a separate class for counting comments?
here's how it will look:
```rb
comments = Judges::Comments.new(octo: Fbe.octo, github_graph: Fbe.github_graph, pull_request: pl)
fact.comments = comments.total
fact.comments_to_code = comments.to_code
fact.comments_by_author = comments.by_author
fact.comments_by_reviewers = comments.by_reviewers
fact.comments_appreciated = comments.appreciated
fact.comments_resolved = comments.resolved
 ```
 or would it be easier just to add a method similar to others, such as `self.fetch_contributors` and `self.fetch_release_info`?
It's just that we get a procedural code style in the `github-events.rb`...

**Comment by yegor256** [comment]
@Suban05 you can make a function instead, that would return a hash: `{ total: 33, to_code: 747, by_author: 34243, ...}`. It's OK to have procedural style inside this script.
