### ISSUE TITLE
new attributes `failed_builds` and `succeeded_builds` for `pull-was-merged`

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#214]
When we create `pull-was-merged` in `github-events.rb`, let's ask GitHub API for the number of succeeded and failed workflow builds in this pull request. Let's save this number as `failed_builds` and `succeeded_builds` attributes into the fact.

**Comment by Suban05** [comment]
@yegor256 May I take this one?

**Comment by yegor256** [comment]
@Suban05 please, go ahead

**Comment by Suban05** [comment]
@yegor256 I don't get completely, we need to get workflows builds in the all commits of a pull request, or we need to get workflows builds on the latest pull request commit (by the `head.sha` field of the pull request)?

**Comment by yegor256** [comment]
@Suban05 only the latest, by the `head.sha`

**Comment by Suban05** [comment]
@yegor256 thanks!
