### ISSUE TITLE
strange behaviour of tests

### ISSUE THREAD

**Issue by Suban05** [zerocracy/judges-action#216]
I want to add a new test to `test/judges/test-github-events.rb`
I try to add similar example:

```rb
def test_must_skip_event_when_pr_author_equals_actor
  WebMock.disable_net_connect!
  # call stub_request
  $fb = Factbase.new
  $global = {}
  $local = {}
  $options = Judges::Options.new({ 'repositories' => 'foo/foo' })
  $loog = Loog::VERBOSE
  require_relative '../../judges/github-events/github-events'
  f = $fb.query('(eq what "pull-was-reviewed")').each.to_a
  assert_equal(42, f.first.who)
end
```

Then I run tests via `bundle exec rake`

And an error occurs `undefined method who for nil`

Moreover, the error can occur in different tests every time. This may be the first test of `test_create_tag_event` or a new test. As far as I understand, the tests are executed in random order, so the position of the error changes. And, as I understand it, the error occurs on the second running test. That is, the first test is running successfully, the second one has an error. I looked in the debugger, in the second test it seems that `Factbase` has no data. There is an assumption that such strange behavior may be due to global variables, but I may be wrong.

**Comment by Suban05** [comment]
@yegor256 I described my problem (https://github.com/zerocracy/judges-action/pull/215)

**Comment by yegor256** [comment]
@Suban05 thanks, let me check

**Comment by 0crat** [comment]
@Suban05 Hey there, bug hunter! 🐛

Awesome job spotting that glitch! You've just bagged yourself 15 points - way to go! 🎉

Finding bugs is like a treasure hunt that makes our project better. Got an eagle eye for anything else that seems off? Don't be shy, [report away](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html)!

Your bug-busting balance is now [+99](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep it up!

Happy hunting! 🕵️‍♂️💻

**Comment by yegor256** [comment]
@Suban05 I believe it's OK now, see the changes of a30a31e If doesn't work still, make a new ticket please.

**Comment by Suban05** [comment]
@yegor256 it works, thanks!
