### ISSUE TITLE
delete lost issues when we can't find them

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#218]
This is what I'm getting from `label-was-attached.rb`: 

```
GET https://api.github.com/repositories/728758275/issues/161/timeline?per_page=100: 404 - Not Found // See: https://docs.github.com/rest/issues/timeline#list-timeline-events-for-an-issue
```

This means that the issue is gone (transferred to another repository). I believe, we should catch this type of error and remove the `issue-was-opened` fact from the factbase.

**Comment by Suban05** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Suban05 please, go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.40`
