### ISSUE TITLE
Sometimes tests fail

### ISSUE THREAD

**Issue by Suban05** [zerocracy/judges-action#219]
If I run tests many times in a row, I sometimes see an error:

```
TestGithubEvents#test_skip_watch_event:
NoMethodError: undefined method `[]' for nil
    /home/suban/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fbe-0.0.36/lib/fbe/fb.rb:34:in `fb'
    /home/suban/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fbe-0.0.36/lib/fbe/iterate.rb:31:in `iterate'
    judges/github-events/github-events.rb:32:in `<top (required)>'
    test/judges/test-github-events.rb:77:in `load'
    test/judges/test-github-events.rb:77:in `test_skip_watch_event'
```

An example of the error can be seen here: https://github.com/zerocracy/judges-action/actions/runs/10225632107/job/28295881921?pr=215

**Comment by Suban05** [comment]
@yegor256 can you check this, please?

**Comment by yegor256** [comment]
@Suban05 should be fixed now. If you still see the problem, open a new ticket please.

**Comment by 0crat** [comment]
@Suban05 Hey there, bug hunter! 🐛 Great job spotting that new bug - you've just snagged yourself 15 points! Your sharp eye is helping us level up our project quality. Got any more [hidden bugs](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) up your sleeve? [Don't hold back](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html), [report away](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html)! Your current score is looking good at [+114](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep those reports coming!

**Comment by Suban05** [comment]
@yegor256 it works, thanks!
