### ISSUE TITLE
`average_reviews_per_pull` into QoS

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#220]
Let's add `average_reviews_per_pull` metric to the `quality-of-service.rb` script. It should calculate the average number of reviews per a pull request.

Maybe relevant to #192

**Comment by Yegorov** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@Yegorov sure, please go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.52`
