### ISSUE TITLE
suffix `action_version` meta if there is a mismatch with the latest on GitHub

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#224]
In `entry.sh`, when we post `action_version` meta let's do a check: go to GitHub and see what is the version of the `zerocracy/judges-action` latest release. If there is a mismatch, let's modify the meta and make it look like this:

```
0.0.38!0.0.39
```

Here, 0.0.38 is the current version being used, while 0.0.39 is the one available on GitHub releases.

**Comment by Yegorov** [comment]
@yegor256 may I try this one?

**Comment by yegor256** [comment]
@Yegorov go ahead, please

**Comment by Suban05** [comment]
@yegor256 please close
