### ISSUE TITLE
`average_triage_time` into QoS

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#227]
Add `average_triage_time` to `quality-of-service` fact, where it's missing. It should be the average time in seconds between `issue-was-opened` and `bug-was-accepted` or `enhancement-was-accepted`.

**Comment by Yegorov** [comment]
@yegor256 Do I understand correctly `bug-was-accepted` and `enhancement-was-accepted` this is the addition of labels to issue? And the time of `X-was-accepted` can be taken from [`label-was-attached` judge](https://github.com/zerocracy/judges-action/blob/master/judges/label-was-attached/label-was-attached.rb)?
Can I try this one?

**Comment by Yegorov** [comment]
@yegor256 And one more clarification, the average value must be calculated for issues of open from `f.since`?

**Comment by yegor256** [comment]
@Yegorov you understand it correctly. It's `f.when`, not `f.since`.

**Comment by Yegorov** [comment]
@yegor256 

> It's f.when, not f.since.

Why from `f.when`?  [`f.when` - is now Time](https://github.com/zerocracy/fbe/blob/f28b01eb3df0ee9ede4b3b3bbcf5bd0caf8fd06d/lib/fbe/regularly.rb#L49)

**Comment by yegor256** [comment]
@Yegorov if you mean the QoS fact, then we should use `since`, but for the `issue-was-opened`, `bug-was-accepted`, and `enhancement-was-accepted` we should use `when`.
