### ISSUE TITLE
`average_backlog_size` is flat

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#240]
Currently, the `average_backlog_size` metric in the `quality-of-service.rb` script doesn't take into account the history of repositories. It simply checks the current average number of issues in repositories. Instead, it should return the average backlog size over the entire period of time from `f.since` until now.

**Comment by Yegorov** [comment]
@yegor256 Do I understand correctly that we need to find all the open issues from the date `f.since` and count them to the average number?

**Comment by Yegorov** [comment]
@yegor256 may I try this one?

**Comment by yegor256** [comment]
@Yegorov I think we should enlist all days from `f.since` until now. Let's say there are 7 days. Then, we go day by day and check how many open issues we had by the end of that day in each repository. If we have 10 repositories, we will get 70 number. Then, we calculate the average of all 70.
