### ISSUE TITLE
Extra symbol `T` in `f.since.utc.iso8601[0..10]`

### ISSUE THREAD

**Issue by Yegorov** [zerocracy/judges-action#244]
In this [file](https://github.com/zerocracy/judges-action/blob/b6b267c73ff57babeb636765b641c9707189d03b/judges/quality-of-service/quality-of-service.rb) `f.since.utc.iso8601[0..10]` return `"2024-08-07T"` with extra symbol `T`

For example:
```ruby
3.3.4 :001 > require 'time'
 => true
3.3.4 :002 > Time.now.utc.iso8601[0..10]
 => "2024-08-07T"
```

May be fix like this:
```ruby
3.3.4 :003 > Time.now.utc.iso8601[0..9]
 => "2024-08-07"
```

Or like this
```ruby
3.3.4 :005 > Time.now.utc.strftime('%Y-%m-%d')
 => "2024-08-07"
```

The second case is more descriptive

@yegor256 What do you think about that?
I can fix it

**Comment by yegor256** [comment]
@Yegorov definitely a bug, thanks!

**Comment by 0crat** [comment]
@Yegorov 🎉 Awesome job reporting a bug! You've earned +15 points, boosting your balance to [+131](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Your keen eye helps us enhance our project's quality. Keep an eye out for anything that [seems off](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) and don't hesitate to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) it. Remember, [bugs are welcome](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) here!
