### ISSUE TITLE
` test_runs_when_run_duration_ms_is_nil` fails

### ISSUE THREAD

**Issue by Suban05** [zerocracy/judges-action#271]
https://github.com/zerocracy/judges-action/actions/runs/10367594772/job/28699376905

**Comment by Suban05** [comment]
@yegor256 we need a test helper that calculates the correct date in the similar tests
can I fix it?

**Comment by yegor256** [comment]
@Suban05 I'm not sure I understand. What is the problem now? Why the test fails?

**Comment by Suban05** [comment]
@yegor256 Yesterday, I fixed a bug #261 and added a test called `test_runs_when_run_duration_ms_is_nil`. I also wrote stub requests everywhere with the date "2024-07-15". For example, `https://api.github.com/repos/foo/foo/actions/runs?created=%3E2024-07-15&per_page=100`. But I didn't realize that the date could change. Yesterday, the tests passed, but today they fail because the date is different

**Comment by 0crat** [comment]
@Suban05 🎉 Awesome job on reporting a new bug! You've earned +10 points, bringing your balance to [+347](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Your keen eye helps us enhance our project's quality. Keep up the great work! If you spot anything else that [seems off](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html), please [don't hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report it](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html). Your contributions are invaluable!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.46`
