### ISSUE TITLE
duplicate `issue-was-closed` fact

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#293]
Check this out: https://github.com/yegor256/judges/issues/84 The issue, apparently, was closed twice. Because of this, GitHub sent two events. We must ignore the second one, if the first one is already in the factbase.

**Comment by tank-bohr** [comment]
@yegor256 what if the issue was reopened and closed again? why it's a problem to have two events in the factbase?

**Comment by yegor256** [comment]
@tank-bohr we assume that an atomic piece of work is an issue. Having two "closed" or "opened" events violates this assumption. Once we have "issue-was-opened", we wait for its closure and pay. End of story. If re-opening happens, we don't pay and don't pay attention to it. We may also punish the person who reopened (but this is for later).

**Comment by tank-bohr** [comment]
@yegor256 Ok. So, it means we should ignore both `issue-was-closed` and `issue-was-opened` if we already have them in the factbase, correct?

BTW, in my opinion it's a bit too strict. I'm myself messing up with the issues number all the time as they are flying around across multiple repositories. And this could lead to accidental issue closing. I believe there should be a way to mitigate situations of this kind.

**Comment by yegor256** [comment]
@tank-bohr yes, for now we should ignore both `issue-was-closed` and `issue-was-opened`
