### ISSUE TITLE
code review comments are not the same as formal code review

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#298]
Look at this ticket: https://github.com/zerocracy/judges-action/pull/294 Here, only one formal code review was submitted (by @Suban05), while other two participants (@yegor256 and @Yegorov) only posted comments. However, the `github-events.rb` script created three `pull-was-reviewed` facts. This is a mistake, only one fact should have been created.

**Comment by Suban05** [comment]
@yegor256 I can help

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.48`
