### ISSUE TITLE
Add test cases for `total_releases`, `total_stars`, `total_forks` in DoT

### ISSUE THREAD

**Issue by Yegorov** [zerocracy/judges-action#372]
@yegor256 As you can see, there are no test cases for  `total_releases`, `total_stars`, `total_forks` in [test Dimensions of Terrain](https://github.com/zerocracy/judges-action/blob/fa4f80488faab96e00e7292469d5596fb66cfdba/test/judges/test-dimensions-of-terrain.rb#L33)
It would probably be right to add them. What do you think? 
I can do this.

**Comment by yegor256** [comment]
@Yegorov good idea, please implement them

**Comment by 0crat** [comment]
@Yegorov Thank you for reporting a new bug! 🐛 As per our team policy, you've earned **8** points for your valuable contribution. Your keen eye helps improve our project's quality. If you spot anything else that [doesn't look](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) quite right, please [don't hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) it. Keep up the great work! Your current balance is [+154](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).
